
version: '3'

services:
  api:
    image: crshlab/cicd_starter:0.1.22
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      PORT: 
    ports:
      - PORT:80 # [local]:[exposed]

  db:
    container_name: devBEX_store   
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD:
    ports:
      - 5432:5432