version: 2.1
workflow: 
  test_and_build:
    jobs:
      test:
        docker:
          # specify the version you desire here
          - image: circleci/node:9

        steps:
          - run: cd api && npm install
          - run: cd api && npm test
