version: 2.1
workflow: 
  ci:
    jobs:
      test:
        docker:
          # specify the version you desire here
          - image: circleci/node:12.18

        steps:
          - run: cd api && npm install
          - run: cd api && npm test
